FROM gcr.io/dataflow-templates-base/python3-template-launcher-base

WORKDIR /template

COPY requirements-dataflow.txt /template/requirements-dataflow.txt
COPY requirements.txt /template/requirements.txt
RUN pip install --no-cache-dir -r /template/requirements-dataflow.txt

COPY setup.py /template/setup.py
COPY src /template/src

ENV FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE="/template/requirements-dataflow.txt"
ENV FLEX_TEMPLATE_PYTHON_SETUP_FILE="/template/setup.py"
ENV FLEX_TEMPLATE_PYTHON_PY_FILE="/template/src/beam_dataflow.py"
